const CATEGORIES_FETCH_FAILED  = 'CATEGORIES_FETCH_FAILED',
      CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS',
      CATEGORIES_REQUESTED     = 'CATEGORIES_REQUESTED',

      POSTS_FETCH_FAILED  = 'POSTS_FETCH_FAILED',
      POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS',
      POSTS_REQUESTED     = 'POSTS_REQUESTED',

      POSTS_SORT = 'POSTS_SORT',

      POSTS_ADD_FAILED    = 'POSTS_ADD_FAILED',
      POSTS_ADD_REQUESTED = 'POSTS_ADD_REQUESTED',
      POSTS_ADD_SUCCESS   = 'POSTS_ADD_SUCCESS',

      POSTS_DELETE_FAILED    = 'POSTS_DELETE_FAILED',
      POSTS_DELETE_REQUESTED = 'POSTS_DELETE_REQUESTED',
      POSTS_DELETE_SUCCESS   = 'POSTS_DELETE_SUCCESS',

      POSTS_EDIT_FAILED    = 'POSTS_EDIT_FAILED',
      POSTS_EDIT_REQUESTED = 'POSTS_EDIT_REQUESTED',
      POSTS_EDIT_SUCCESS   = 'POSTS_EDIT_SUCCESS',

      POSTS_VOTE_FAILED    = 'POSTS_VOTE_FAILED',
      POSTS_VOTE_REQUESTED = 'POSTS_VOTE_REQUESTED',
      POSTS_VOTE_SUCCESS   = 'POSTS_VOTE_SUCCESS',

      COMMENTS_FETCH_FAILED  = 'COMMENTS_FETCH_FAILED',
      COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS',
      COMMENTS_REQUESTED     = 'COMMENTS_REQUESTED',

      COMMENTS_ADD_FAILED    = 'COMMENTS_ADD_FAILED',
      COMMENTS_ADD_SUCCESS   = 'COMMENTS_ADD_SUCCESS',
      COMMENTS_ADD_REQUESTED = 'COMMENTS_ADD_REQUESTED',

      COMMENTS_DELETE_FAILED    = 'COMMENTS_DELETE_FAILED',
      COMMENTS_DELETE_SUCCESS   = 'COMMENTS_DELETE_SUCCESS',
      COMMENTS_DELETE_REQUESTED =' COMMENTS_DELETE_REQUESTED',

      COMMENTS_EDIT_FAILED    = 'COMMENTS_EDIT_FAILED',
      COMMENTS_EDIT_SUCCESS   = 'COMMENTS_EDIT_SUCCESS',
      COMMENTS_EDIT_REQUESTED = 'COMMENTS_EDIT_REQUESTED',

      COMMENTS_VOTE_FAILED    = 'COMMENTS_VOTE_FAILED',
      COMMENTS_VOTE_REQUESTED = 'COMMENTS_VOTE_REQUESTED',
      COMMENTS_VOTE_SUCCESS   = 'COMMENTS_VOTE_SUCCESS';

export {
  CATEGORIES_FETCH_FAILED,
  CATEGORIES_FETCH_SUCCESS,
  CATEGORIES_REQUESTED,
  POSTS_FETCH_FAILED,
  POSTS_FETCH_SUCCESS,
  POSTS_REQUESTED,
  POSTS_SORT,
  POSTS_ADD_FAILED,
  POSTS_ADD_REQUESTED,
  POSTS_ADD_SUCCESS,
  POSTS_DELETE_FAILED,
  POSTS_DELETE_REQUESTED,
  POSTS_DELETE_SUCCESS,
  POSTS_EDIT_FAILED,
  POSTS_EDIT_REQUESTED,
  POSTS_EDIT_SUCCESS,
  POSTS_VOTE_FAILED,
  POSTS_VOTE_REQUESTED,
  POSTS_VOTE_SUCCESS,
  COMMENTS_FETCH_FAILED,
  COMMENTS_FETCH_SUCCESS,
  COMMENTS_REQUESTED,
  COMMENTS_ADD_FAILED,
  COMMENTS_ADD_REQUESTED,
  COMMENTS_ADD_SUCCESS,
  COMMENTS_DELETE_FAILED,
  COMMENTS_DELETE_REQUESTED,
  COMMENTS_DELETE_SUCCESS,
  COMMENTS_EDIT_FAILED,
  COMMENTS_EDIT_REQUESTED,
  COMMENTS_EDIT_SUCCESS,
  COMMENTS_VOTE_FAILED,
  COMMENTS_VOTE_REQUESTED,
  COMMENTS_VOTE_SUCCESS
};
