const CATEGORIES_FETCH_FAILED  = 'CATEGORIES_FETCH_FAILED';
const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS';
const CATEGORIES_REQUESTED     = 'CATEGORIES_REQUESTED';

export {
  CATEGORIES_FETCH_FAILED,
  CATEGORIES_FETCH_SUCCESS,
  CATEGORIES_REQUESTED
};
