const CATEGORIES_FETCH_FAILED  = 'CATEGORIES_FETCH_FAILED',
      CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS',
      CATEGORIES_REQUESTED     = 'CATEGORIES_REQUESTED',

      POSTS_FETCH_FAILED  = 'POSTS_FETCH_FAILED',
      POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS',
      POSTS_REQUESTED     = 'POSTS_REQUESTED',

      POSTS_SORT = 'POSTS_SORT';

export {
  CATEGORIES_FETCH_FAILED,
  CATEGORIES_FETCH_SUCCESS,
  CATEGORIES_REQUESTED,
  POSTS_FETCH_FAILED,
  POSTS_FETCH_SUCCESS,
  POSTS_REQUESTED,
  POSTS_SORT
};
